name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # OIDC 인증을 위한 권한 추가
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build JAR
        run: ./gradlew build

      - name: List all files in workspace
        run: |
          echo "=== 현재 디렉토리 확인 ==="
          pwd
          echo "=== 최상위 디렉토리 리스트 ==="
          ls -lah
          echo "=== 현재 경로 폴더 구조 확인 ==="
          ls -lah ./apps/user-app/build/libs
          echo "=== build 폴더 구조 확인 ==="
          ls -lah ./build/
          echo "=== build/libs 폴더 구조 확인 ==="
          ls -lah ./build/libs/

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::491085395207:role/github-action-role
          aws-region: ap-northeast-2

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve
        working-directory: ./terraform

      - name: Upload JAR to S3
        run: |
          aws s3 cp ./apps/user-app/build/libs/user-app-module.jar s3://deploy-s3-medalist/user-app-module.jar

      - name: Deploy JAR to EC2 via SSM
        run: |
#          aws ssm send-command \
#            --document-name "AWS-RunShellScript" \
#            --targets "Key=instanceIds,Values=i-xxxxxxxxxxxxxx" \
#            --parameters 'commands=["aws s3 cp s3://deploy-s3-medalist/user-app-module.jar /home/ubuntu/user-app-module.jar", "sudo systemctl restart user-app-module"]' \
#            --region ap-northeast-2
          
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=$(aws ec2 describe-instances \
              --filters "Name=tag:Name,Values=AppServer" 
              --output text --region ap-northeast-2)" \
            --parameters 'commands=["aws s3 cp s3://deploy-s3-medalist/user-app-module.jar /home/ubuntu/user-app-module.jar", "sudo systemctl restart user-app-module"]' \
            --region ap-northeast-2
